# playbook is a list of plays
- name: PLAY-1
  hosts: localhost
  tasks:
  - name: PLAY-1 and TASK-1
    ansiblle.builtin.debug:
      msg: "Hello from PLAY-1 and TASK-1"
    
- name: PLAY-2
  hosts: localhost
  tasks:
  - name: PLAY-2 and TASK-2
    ansible.builtin.debug:
      msg: "Hello from PLAT-2 and TASK-2"