- name: conditions
  hosts: localhost
  tasks: 
  - name: check roboshop user exists or not
    ansible.builtin.command: id roboshop
    register: user # user is a variable name
    ignore_erroes: true # ansible will not exit even it got error

  - name: print variable value
    ansible.builtin.debug:
      msg: "User output is: {{user}}"
